apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellipaat-app
  labels:
    app: intellipaat-app
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: intellipaat-app
  template:
    metadata:
      labels:
        app: intellipaat-app
    spec:
      containers:
        - name: intellipaat-app
          image: pankajs2284/intellipaat-app:latest 
          ports:
            - containerPort: 8191 
