apiVersion: v1
kind: Service
metadata:
  name: service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: intellipaat-app
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
    - protocol: TCP
      port: 8191 
      targetPort: 8191 